# Generated by Django 2.1.4 on 2019-04-21 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False)),
                ('journey_date', models.DateField()),
                ('journey_time', models.TimeField()),
                ('seat_no', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0)),
                ('car_model', models.CharField(max_length=40)),
                ('car_no', models.CharField(max_length=20)),
                ('fare', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pay_mode', models.CharField(choices=[('OFFLINE', 'Ofline'), ('ONLINE', 'Online')], default='OFFLINE', max_length=15)),
                ('source_location', models.CharField(max_length=300)),
                ('destination_location', models.CharField(max_length=300)),
            ],
        ),
    ]
