# Generated by Django 2.1.4 on 2019-04-21 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('fare', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
