# Generated by Django 2.1.4 on 2019-04-21 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('placeRide', '0002_placeride_user'),
        ('searchRide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookride',
            name='ride_acceptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookride',
            name='ride_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeRide.PlaceRide'),
        ),
        migrations.AddField(
            model_name='bookride',
            name='ride_placer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placer', to=settings.AUTH_USER_MODEL),
        ),
    ]
